#! /usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

$faker = Faker\Factory::create();
$color = new Console_Color2();

echo $color->convert("%gFull Name:%n ") . $faker->name . "\n";
echo $color->convert("%gUsername:%n  ") . $faker->username . "\n";